### ISSUE TITLE
USER STORY: Easily Navigate and Find Content

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/gamers_insight-CRUD-Blog-App#1]
As a **visitor**, I want to easily navigate the blog and find content that interests me, so I can quickly access the information I'm looking for.

## Acceptance Criteria: 

- Acceptance Criteria 1: Users can easily find the main navigation menu on the blog.

- Acceptance Criteria 2: Clicking on a category leads to a page displaying related articles.

- Acceptance Criteria 3: Clicking on a blog post leads to a page displaying the full post article.

## Tasks: 

- [x] Design and implement a clear and prominent navigation menu.
- [x] Create and style category section that display relevant articles dedicated to the category.
- [x] Make sure that the navigation menu are responsive and looking good at all devices.

**Comment by KimBergstroem** [comment]
The last task about Create and style category section will be implemented tomorrow ( 2023-09-17) and therebefore i will drag this user story to sprint 3.

**Comment by KimBergstroem** [comment]
Finished the last task in this issue, were the category section have been created. This issue are now fnished and moved to finish section in the board.
