### ISSUE TITLE
USER STORY: Edit or Delete Own Articles and Comments

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/gamers_insight-CRUD-Blog-App#10]
As a **registered user**, I want to have the ability to edit or delete my own articles and comments.

 
## Acceptance Criteria: 

- Acceptance Criteria 1: Users can access an "Edit" and "Delete" option for their own articles.
- Acceptance Criteria 2: Users can access an "Edit" and "Delete" option for their own comments.
- Acceptance Criteria 3: Deleted content is removed from public view but may be retained for moderation purposes.
- Acceptance Criteria 4: Edited content displays an edit timestamp. 

## Tasks: 

- [x] Implement "Edit" and "Delete" options for user articles.
- [x] Implement "Edit" and "Delete" options for user comments.
- [x] Develop a mechanism for retaining deleted content for moderation.
- [x] Ensure edited content displays an edit timestamp.

**Comment by KimBergstroem** [comment]
Last task, Develop a mechanism for retaining deleted content for moderation might be a feature issue. User have a page "My Articles" were user can search and find articles that is created. In this page the feature will be implemented.
