### ISSUE TITLE
Planning and Documentation

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/gamers_insight-CRUD-Blog-App#18]
## Tasks: 

- [x] Plan Sprint (Must do)
- [x] Create and write readme.md (Must do)
- [x] Design Database Schema (Should do)
- [x] Create the wireframes (Should do)

**Comment by KimBergstroem** [comment]
Planning Sprints and user stories with MoSCoW principles done along with creating the readme.

**Comment by KimBergstroem** [comment]
Wireframes are created along with color design thinking. This is updated in readme.

**Comment by KimBergstroem** [comment]
Completed the last task. Finalized the database schema and added it to the README file. This issue is now successfully resolved.
