### ISSUE TITLE
Set Up Project Skeleton

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/gamers_insight-CRUD-Blog-App#19]
**Description:** Build the basic structure of the project, including setting up the database, establishing frontend-backend connections, and installing necessary packages. 

**Tasks:**
- [x] Set up a virtual environment for the project to isolate dependencies.
- [x] Install Django and create the project's main directory structure.
- [x] Install all necessary packages that is needed.
- [x] Configure database settings in the project's settings file.
- [x] Generate database migrations and apply them to create the necessary tables.
- [x] Set up a basic static file management system.
- [x] Set up URL routing 
- [x] Create initial HTML templates for the homepage.

**Comment by KimBergstroem** [comment]
Two first tasks are done. Set up virtual environment, created django project and app. Installed dependencies for cloudinary as well.

**Comment by KimBergstroem** [comment]
Added to Sprint 2, as all the template and routing is not finished.
