### ISSUE TITLE
USER STORY: Create a Personalized Profile

### ISSUE THREAD

**Issue by KimBergstroem** [KimBergstroem/gamers_insight-CRUD-Blog-App#5]
As a **visitor**, I want to have the option to subscribe to a newsletter to receive updates on new articles and gaming news.

 
## Acceptance Criteria: 

- Acceptance Criteria 1: Registered users can access a "Profile" section.
- Acceptance Criteria 1: Users can upload a profile picture.
- Acceptance Criteria 1: Users can enter and save their gaming interests in their profile.
- Acceptance Criteria 1: The profile information is editable by the user.

## Tasks: 

- [x] Create a "Profile" section in the user interface.
- [x] Implement a profile picture upload feature.
- [x] Develop a form for users to enter and save their gaming interests.
- [x] Enable profile editing functionality.

**Comment by KimBergstroem** [comment]
Updated the profile editing functionality. When user press "Update" the form comes preloaded with users current data that is saved.
